language: cpp
compiler:
  - gcc
install:
  - sudo apt-get install gcc-multilib g++-multilib cmake
before_script:
  - cmake . -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32
script:
  - make
  - make package
