version: '{build}'

configuration:
  - RelWithDebInfo

before_build:
  - cmake . 

build_script:
  - cmake --build . --config %CONFIGURATION%
  - cmake --build . --config %CONFIGURATION% --target package

artifacts:
  - path: profiler-*-win32.zip
    name: Binaries
