version: '{build}'

configuration:
  - Debug

before_build:
  - cmake . -G "Visual Studio 10 2010"

build_script:
  - cmake --build . --config %CONFIGURATION%
  - cmake --build . --config %CONFIGURATION% --target package

artifacts:
  - path: profiler-*-win32.zip
    name: Binaries

  - path: src/Debug/profiler.pdb
    name: Debug info
